BIRD_IMAGES: tuple[str, ...] = (
    "Artboard1.svg",
    "Artboard2.svg",
    "Artboard3.svg",
    "Artboard4.svg",
    "Artboard5.svg",
    "Artboard6.svg",
    "Artboard7.svg",
    "Artboard8.svg",
    "Artboard9.svg",
    "Artboard10.svg",
    "Artboard11.svg",
    "Artboard12.svg",
    "Artboard13.svg",
    "Artboard14.svg",
    "Artboard16.svg",
    "Artboard17.svg",
    "Artboard18.svg",
    "Artboard19.svg",
    "Artboard20.svg",
    "Artboard21.svg",
    "Artboard22.svg",
    "Artboard23.svg",
    "Artboard25.svg",
    "Artboard26.svg",
    "Artboard27.svg",
    "Artboard28.svg",
)

BIRD_IMAGE_COUNT = len(BIRD_IMAGES)
