# Generated by Django 5.2.15 on 2026-06-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="bird_image",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="bird_assignment_pool",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
