# Generated by Django 5.2.15 on 2026-08-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_status_flying_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_section_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('flying_later', 'Flying Later'), ('custom', 'Custom'), ('done', 'Done'), ('abandoned', 'Abandoned')], db_index=True, default='active', max_length=20),
        ),
    ]
