# Generated by Django 5.2.15 on 2026-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_custom_section_name_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=840),
        ),
    ]
